package kotlin.reflect.jvm.internal.impl.util;

import android.gov.nist.core.Separators;
import android.gov.nist.javax.sip.header.ims.ParameterNamesIms;
import java.util.Map;
import java.util.Set;
import kotlin.jvm.internal.AbstractC16544l;
import kotlin.reflect.jvm.internal.impl.name.Name;
import mm.C17309l;
import p1113xn.C21319m;
import p909nm.AbstractC17659D;
import p909nm.AbstractC17665J;
import p909nm.AbstractC17678l;

/* JADX INFO: loaded from: classes2.dex */
public final class OperatorNameConventions {
    public static final Set<Name> ALL_BINARY_OPERATION_NAMES;
    public static final Name AND;
    public static final Set<Name> ASSIGNMENT_OPERATIONS;
    public static final Set<Name> BINARY_OPERATION_NAMES;
    public static final Set<Name> BITWISE_OPERATION_NAMES;
    public static final Name COMPARE_TO;
    public static final C21319m COMPONENT_REGEX;
    public static final Name CONTAINS;
    public static final Name DEC;
    public static final Set<Name> DELEGATED_PROPERTY_OPERATORS;
    public static final Name DIV;
    public static final Name DIV_ASSIGN;
    public static final Name EQUALS;
    public static final Name GET;
    public static final Name GET_VALUE;
    public static final Name HASH_CODE;
    public static final Name HAS_NEXT;
    public static final Name INC;
    public static final OperatorNameConventions INSTANCE = new OperatorNameConventions();
    public static final Name INV;
    public static final Name INVOKE;
    public static final Name ITERATOR;
    public static final Name MINUS;
    public static final Name MINUS_ASSIGN;
    public static final Name MOD;
    public static final Name MOD_ASSIGN;
    public static final Map<Name, Name> MOD_OPERATORS_REPLACEMENT;
    public static final Name NEXT;
    public static final Name NOT;
    public static final Set<Name> NUMBER_CONVERSIONS;

    /* JADX INFO: renamed from: OR */
    public static final Name f53298OR;
    public static final Name PLUS;
    public static final Name PLUS_ASSIGN;
    public static final Name PROVIDE_DELEGATE;
    public static final Name RANGE_TO;
    public static final Name RANGE_UNTIL;
    public static final Name REM;
    public static final Name REM_ASSIGN;
    public static final Name SET;
    public static final Name SET_VALUE;
    public static final Name SHL;
    public static final Name SHR;
    public static final Set<Name> SIMPLE_BINARY_OPERATION_NAMES;
    public static final Set<Name> SIMPLE_BITWISE_OPERATION_NAMES;
    public static final Set<Name> SIMPLE_UNARY_OPERATION_NAMES;
    public static final Set<Name> STATEMENT_LIKE_OPERATORS;
    public static final Name TIMES;
    public static final Name TIMES_ASSIGN;
    public static final Name TO_BYTE;
    public static final Name TO_CHAR;
    public static final Name TO_DOUBLE;
    public static final Name TO_FLOAT;
    public static final Name TO_INT;
    public static final Name TO_LONG;
    public static final Name TO_SHORT;
    public static final Name TO_STRING;
    public static final Name UNARY_MINUS;
    public static final Set<Name> UNARY_OPERATION_NAMES;
    public static final Name UNARY_PLUS;
    public static final Name USHR;
    public static final Name XOR;

    /* JADX INFO: renamed from: a */
    public static final Object f53299a;

    static {
        Name nameIdentifier = Name.identifier("getValue");
        AbstractC16544l.m18093f(nameIdentifier, "identifier(...)");
        GET_VALUE = nameIdentifier;
        Name nameIdentifier2 = Name.identifier("setValue");
        AbstractC16544l.m18093f(nameIdentifier2, "identifier(...)");
        SET_VALUE = nameIdentifier2;
        Name nameIdentifier3 = Name.identifier("provideDelegate");
        AbstractC16544l.m18093f(nameIdentifier3, "identifier(...)");
        PROVIDE_DELEGATE = nameIdentifier3;
        Name nameIdentifier4 = Name.identifier("equals");
        AbstractC16544l.m18093f(nameIdentifier4, "identifier(...)");
        EQUALS = nameIdentifier4;
        Name nameIdentifier5 = Name.identifier("hashCode");
        AbstractC16544l.m18093f(nameIdentifier5, "identifier(...)");
        HASH_CODE = nameIdentifier5;
        Name nameIdentifier6 = Name.identifier("compareTo");
        AbstractC16544l.m18093f(nameIdentifier6, "identifier(...)");
        COMPARE_TO = nameIdentifier6;
        Name nameIdentifier7 = Name.identifier("contains");
        AbstractC16544l.m18093f(nameIdentifier7, "identifier(...)");
        CONTAINS = nameIdentifier7;
        Name nameIdentifier8 = Name.identifier("invoke");
        AbstractC16544l.m18093f(nameIdentifier8, "identifier(...)");
        INVOKE = nameIdentifier8;
        Name nameIdentifier9 = Name.identifier("iterator");
        AbstractC16544l.m18093f(nameIdentifier9, "identifier(...)");
        ITERATOR = nameIdentifier9;
        Name nameIdentifier10 = Name.identifier("get");
        AbstractC16544l.m18093f(nameIdentifier10, "identifier(...)");
        GET = nameIdentifier10;
        Name nameIdentifier11 = Name.identifier("set");
        AbstractC16544l.m18093f(nameIdentifier11, "identifier(...)");
        SET = nameIdentifier11;
        Name nameIdentifier12 = Name.identifier("next");
        AbstractC16544l.m18093f(nameIdentifier12, "identifier(...)");
        NEXT = nameIdentifier12;
        Name nameIdentifier13 = Name.identifier("hasNext");
        AbstractC16544l.m18093f(nameIdentifier13, "identifier(...)");
        HAS_NEXT = nameIdentifier13;
        Name nameIdentifier14 = Name.identifier("toString");
        AbstractC16544l.m18093f(nameIdentifier14, "identifier(...)");
        TO_STRING = nameIdentifier14;
        COMPONENT_REGEX = new C21319m("component\\d+");
        Name nameIdentifier15 = Name.identifier("and");
        AbstractC16544l.m18093f(nameIdentifier15, "identifier(...)");
        AND = nameIdentifier15;
        Name nameIdentifier16 = Name.identifier("or");
        AbstractC16544l.m18093f(nameIdentifier16, "identifier(...)");
        f53298OR = nameIdentifier16;
        Name nameIdentifier17 = Name.identifier("xor");
        AbstractC16544l.m18093f(nameIdentifier17, "identifier(...)");
        XOR = nameIdentifier17;
        Name nameIdentifier18 = Name.identifier("inv");
        AbstractC16544l.m18093f(nameIdentifier18, "identifier(...)");
        INV = nameIdentifier18;
        Name nameIdentifier19 = Name.identifier("shl");
        AbstractC16544l.m18093f(nameIdentifier19, "identifier(...)");
        SHL = nameIdentifier19;
        Name nameIdentifier20 = Name.identifier("shr");
        AbstractC16544l.m18093f(nameIdentifier20, "identifier(...)");
        SHR = nameIdentifier20;
        Name nameIdentifier21 = Name.identifier("ushr");
        AbstractC16544l.m18093f(nameIdentifier21, "identifier(...)");
        USHR = nameIdentifier21;
        Name nameIdentifier22 = Name.identifier("inc");
        AbstractC16544l.m18093f(nameIdentifier22, "identifier(...)");
        INC = nameIdentifier22;
        Name nameIdentifier23 = Name.identifier("dec");
        AbstractC16544l.m18093f(nameIdentifier23, "identifier(...)");
        DEC = nameIdentifier23;
        Name nameIdentifier24 = Name.identifier("plus");
        AbstractC16544l.m18093f(nameIdentifier24, "identifier(...)");
        PLUS = nameIdentifier24;
        Name nameIdentifier25 = Name.identifier("minus");
        AbstractC16544l.m18093f(nameIdentifier25, "identifier(...)");
        MINUS = nameIdentifier25;
        Name nameIdentifier26 = Name.identifier("not");
        AbstractC16544l.m18093f(nameIdentifier26, "identifier(...)");
        NOT = nameIdentifier26;
        Name nameIdentifier27 = Name.identifier("unaryMinus");
        AbstractC16544l.m18093f(nameIdentifier27, "identifier(...)");
        UNARY_MINUS = nameIdentifier27;
        Name nameIdentifier28 = Name.identifier("unaryPlus");
        AbstractC16544l.m18093f(nameIdentifier28, "identifier(...)");
        UNARY_PLUS = nameIdentifier28;
        Name nameIdentifier29 = Name.identifier("times");
        AbstractC16544l.m18093f(nameIdentifier29, "identifier(...)");
        TIMES = nameIdentifier29;
        Name nameIdentifier30 = Name.identifier("div");
        AbstractC16544l.m18093f(nameIdentifier30, "identifier(...)");
        DIV = nameIdentifier30;
        Name nameIdentifier31 = Name.identifier(ParameterNamesIms.MOD);
        AbstractC16544l.m18093f(nameIdentifier31, "identifier(...)");
        MOD = nameIdentifier31;
        Name nameIdentifier32 = Name.identifier("rem");
        AbstractC16544l.m18093f(nameIdentifier32, "identifier(...)");
        REM = nameIdentifier32;
        Name nameIdentifier33 = Name.identifier("rangeTo");
        AbstractC16544l.m18093f(nameIdentifier33, "identifier(...)");
        RANGE_TO = nameIdentifier33;
        Name nameIdentifier34 = Name.identifier("rangeUntil");
        AbstractC16544l.m18093f(nameIdentifier34, "identifier(...)");
        RANGE_UNTIL = nameIdentifier34;
        Name nameIdentifier35 = Name.identifier("timesAssign");
        AbstractC16544l.m18093f(nameIdentifier35, "identifier(...)");
        TIMES_ASSIGN = nameIdentifier35;
        Name nameIdentifier36 = Name.identifier("divAssign");
        AbstractC16544l.m18093f(nameIdentifier36, "identifier(...)");
        DIV_ASSIGN = nameIdentifier36;
        Name nameIdentifier37 = Name.identifier("modAssign");
        AbstractC16544l.m18093f(nameIdentifier37, "identifier(...)");
        MOD_ASSIGN = nameIdentifier37;
        Name nameIdentifier38 = Name.identifier("remAssign");
        AbstractC16544l.m18093f(nameIdentifier38, "identifier(...)");
        REM_ASSIGN = nameIdentifier38;
        Name nameIdentifier39 = Name.identifier("plusAssign");
        AbstractC16544l.m18093f(nameIdentifier39, "identifier(...)");
        PLUS_ASSIGN = nameIdentifier39;
        Name nameIdentifier40 = Name.identifier("minusAssign");
        AbstractC16544l.m18093f(nameIdentifier40, "identifier(...)");
        MINUS_ASSIGN = nameIdentifier40;
        Name nameIdentifier41 = Name.identifier("toDouble");
        AbstractC16544l.m18093f(nameIdentifier41, "identifier(...)");
        TO_DOUBLE = nameIdentifier41;
        Name nameIdentifier42 = Name.identifier("toFloat");
        AbstractC16544l.m18093f(nameIdentifier42, "identifier(...)");
        TO_FLOAT = nameIdentifier42;
        Name nameIdentifier43 = Name.identifier("toLong");
        AbstractC16544l.m18093f(nameIdentifier43, "identifier(...)");
        TO_LONG = nameIdentifier43;
        Name nameIdentifier44 = Name.identifier("toInt");
        AbstractC16544l.m18093f(nameIdentifier44, "identifier(...)");
        TO_INT = nameIdentifier44;
        Name nameIdentifier45 = Name.identifier("toChar");
        AbstractC16544l.m18093f(nameIdentifier45, "identifier(...)");
        TO_CHAR = nameIdentifier45;
        Name nameIdentifier46 = Name.identifier("toShort");
        AbstractC16544l.m18093f(nameIdentifier46, "identifier(...)");
        TO_SHORT = nameIdentifier46;
        Name nameIdentifier47 = Name.identifier("toByte");
        AbstractC16544l.m18093f(nameIdentifier47, "identifier(...)");
        TO_BYTE = nameIdentifier47;
        UNARY_OPERATION_NAMES = AbstractC17678l.m19293P(new Name[]{nameIdentifier22, nameIdentifier23, nameIdentifier28, nameIdentifier27, nameIdentifier26, nameIdentifier18});
        SIMPLE_UNARY_OPERATION_NAMES = AbstractC17678l.m19293P(new Name[]{nameIdentifier28, nameIdentifier27, nameIdentifier26, nameIdentifier18});
        Set<Name> setM19293P = AbstractC17678l.m19293P(new Name[]{nameIdentifier29, nameIdentifier24, nameIdentifier25, nameIdentifier30, nameIdentifier31, nameIdentifier32, nameIdentifier33, nameIdentifier34});
        BINARY_OPERATION_NAMES = setM19293P;
        SIMPLE_BINARY_OPERATION_NAMES = AbstractC17678l.m19293P(new Name[]{nameIdentifier29, nameIdentifier24, nameIdentifier25, nameIdentifier30, nameIdentifier31, nameIdentifier32});
        Set<Name> setM19293P2 = AbstractC17678l.m19293P(new Name[]{nameIdentifier15, nameIdentifier16, nameIdentifier17, nameIdentifier18, nameIdentifier19, nameIdentifier20, nameIdentifier21});
        BITWISE_OPERATION_NAMES = setM19293P2;
        SIMPLE_BITWISE_OPERATION_NAMES = AbstractC17678l.m19293P(new Name[]{nameIdentifier15, nameIdentifier16, nameIdentifier17, nameIdentifier19, nameIdentifier20, nameIdentifier21});
        ALL_BINARY_OPERATION_NAMES = AbstractC17665J.m19266f(AbstractC17665J.m19266f(setM19293P, setM19293P2), AbstractC17678l.m19293P(new Name[]{nameIdentifier4, nameIdentifier7, nameIdentifier6}));
        Set<Name> setM19293P3 = AbstractC17678l.m19293P(new Name[]{nameIdentifier35, nameIdentifier36, nameIdentifier37, nameIdentifier38, nameIdentifier39, nameIdentifier40});
        ASSIGNMENT_OPERATIONS = setM19293P3;
        DELEGATED_PROPERTY_OPERATORS = AbstractC17678l.m19293P(new Name[]{nameIdentifier, nameIdentifier2, nameIdentifier3});
        MOD_OPERATORS_REPLACEMENT = AbstractC17659D.m19244f(new C17309l(nameIdentifier31, nameIdentifier32), new C17309l(nameIdentifier37, nameIdentifier38));
        STATEMENT_LIKE_OPERATORS = AbstractC17665J.m19266f(AbstractC17665J.m19268h(nameIdentifier11), setM19293P3);
        NUMBER_CONVERSIONS = AbstractC17678l.m19293P(new Name[]{nameIdentifier41, nameIdentifier42, nameIdentifier43, nameIdentifier44, nameIdentifier46, nameIdentifier47, nameIdentifier45});
        f53299a = AbstractC17659D.m19244f(new C17309l(nameIdentifier22, "++"), new C17309l(nameIdentifier23, "--"), new C17309l(nameIdentifier28, "+"), new C17309l(nameIdentifier27, "-"), new C17309l(nameIdentifier26, "!"), new C17309l(nameIdentifier29, Separators.STAR), new C17309l(nameIdentifier24, "+"), new C17309l(nameIdentifier25, "-"), new C17309l(nameIdentifier30, Separators.SLASH), new C17309l(nameIdentifier32, Separators.PERCENT), new C17309l(nameIdentifier33, ".."), new C17309l(nameIdentifier34, "..<"));
    }
}
